// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0cHMqnmceGqBEov8Rj6ZfTUzLTgzF4I8',
    appId: '1:388351733974:web:9aed7072355758cb371977',
    messagingSenderId: '388351733974',
    projectId: 'testesilicon',
    authDomain: 'testesilicon.firebaseapp.com',
    storageBucket: 'testesilicon.appspot.com',
    measurementId: 'G-19MG876QR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChnqaRHrAiikkATBFOmFRQK3TwrV74lFA',
    appId: '1:388351733974:android:743a2ec5657da9b9371977',
    messagingSenderId: '388351733974',
    projectId: 'testesilicon',
    storageBucket: 'testesilicon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjzvBsQjVOmnw_H7qi6HQN_vgHPcCvwwg',
    appId: '1:388351733974:ios:22de71c0aeffdce8371977',
    messagingSenderId: '388351733974',
    projectId: 'testesilicon',
    storageBucket: 'testesilicon.appspot.com',
    iosClientId: '388351733974-09uil3t79gq16e183qf28asa1uo7vgrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.projTesteSilicon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjzvBsQjVOmnw_H7qi6HQN_vgHPcCvwwg',
    appId: '1:388351733974:ios:22de71c0aeffdce8371977',
    messagingSenderId: '388351733974',
    projectId: 'testesilicon',
    storageBucket: 'testesilicon.appspot.com',
    iosClientId: '388351733974-09uil3t79gq16e183qf28asa1uo7vgrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.projTesteSilicon',
  );
}
